<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0ff98b257d79128a5ec6e5a23253aa54
{
    public static $files = array (
        'ee320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        'ee0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'eea4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Php80\\' => 51,
            'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Mbstring\\' => 54,
            'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 51,
            'ExpressionEngine\\Dependency\\Sabberworm\\CSS\\' => 43,
            'ExpressionEngine\\Dependency\\Psr\\Clock\\' => 38,
            'ExpressionEngine\\Dependency\\Psr\\Cache\\' => 38,
            'ExpressionEngine\\Dependency\\PhpOption\\' => 38,
            'ExpressionEngine\\Dependency\\ParagonIE\\ConstantTime\\' => 51,
            'ExpressionEngine\\Dependency\\OTPHP\\' => 34,
            'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => 53,
            'ExpressionEngine\\Dependency\\League\\Flysystem\\Cached\\' => 52,
            'ExpressionEngine\\Dependency\\League\\Flysystem\\' => 45,
            'ExpressionEngine\\Dependency\\IPLib\\' => 34,
            'ExpressionEngine\\Dependency\\GrahamCampbell\\ResultType\\' => 54,
            'ExpressionEngine\\Dependency\\Dotenv\\' => 35,
            'ExpressionEngine\\Dependency\\DASPRiD\\Enum\\' => 41,
            'ExpressionEngine\\Dependency\\BaconQrCode\\' => 40,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'ExpressionEngine\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'ExpressionEngine\\Dependency\\Sabberworm\\CSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/src',
        ),
        'ExpressionEngine\\Dependency\\Psr\\Clock\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'ExpressionEngine\\Dependency\\Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'ExpressionEngine\\Dependency\\PhpOption\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoption/phpoption/src/PhpOption',
        ),
        'ExpressionEngine\\Dependency\\ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),
        'ExpressionEngine\\Dependency\\OTPHP\\' => 
        array (
            0 => __DIR__ . '/..' . '/expressionengine/otphp/src',
        ),
        'ExpressionEngine\\Dependency\\League\\MimeTypeDetection\\' => 
        array (
            0 => __DIR__ . '/..' . '/expressionengine/mime-type-detection/src',
        ),
        'ExpressionEngine\\Dependency\\League\\Flysystem\\Cached\\' => 
        array (
            0 => __DIR__ . '/..' . '/expressionengine/flysystem-cached-adapter/src',
        ),
        'ExpressionEngine\\Dependency\\League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/expressionengine/flysystem/src',
        ),
        'ExpressionEngine\\Dependency\\IPLib\\' => 
        array (
            0 => __DIR__ . '/..' . '/mlocati/ip-lib/src',
        ),
        'ExpressionEngine\\Dependency\\GrahamCampbell\\ResultType\\' => 
        array (
            0 => __DIR__ . '/..' . '/graham-campbell/result-type/src',
        ),
        'ExpressionEngine\\Dependency\\Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
        'ExpressionEngine\\Dependency\\DASPRiD\\Enum\\' => 
        array (
            0 => __DIR__ . '/..' . '/dasprid/enum/src',
        ),
        'ExpressionEngine\\Dependency\\BaconQrCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/expressionengine/bacon-qr-code/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'ExpressionEngine\\Dependency\\Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'ExpressionEngine\\Dependency\\PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'ExpressionEngine\\Dependency\\Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'ExpressionEngine\\Dependency\\UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'ExpressionEngine\\Dependency\\ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0ff98b257d79128a5ec6e5a23253aa54::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0ff98b257d79128a5ec6e5a23253aa54::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0ff98b257d79128a5ec6e5a23253aa54::$classMap;

        }, null, ClassLoader::class);
    }
}
